#!/bin/bash

(cd ./books/BIBLE          && make)
(cd ./books/SMALL          && make)
(cd ./books/LARGE          && make)
(cd ./books/MINOR          && make)
(cd ./books/OT             && make)
(cd ./books/NT             && make)
(cd ./books/REVERSED       && make)

(cd ./books/2john          && make)
(cd ./books/2peter         && make)
(cd ./books/2thessalonians && make)
(cd ./books/3john          && make)
(cd ./books/habakkuk       && make)
(cd ./books/haggai         && make)
(cd ./books/jonah          && make)
(cd ./books/jude           && make)
(cd ./books/mark           && make)
(cd ./books/nahum          && make)
(cd ./books/obadiah        && make)
(cd ./books/philemon       && make)
(cd ./books/titus          && make)
(cd ./books/zephaniah      && make)
