#!/bin/bash

# (cd ./books/BIBLE          && make)
# (cd ./books/SMALL          && make)
# (cd ./books/LARGE          && make)
# (cd ./books/MINOR          && make)
# (cd ./books/OT             && make)
# (cd ./books/NT             && make)
# (cd ./books/REVERSED       && make)

(cd ./books/1acts          && make)
(cd ./books/1chronicles    && make)
(cd ./books/1corinthians   && make)
(cd ./books/1isaiah        && make)
(cd ./books/1john          && make)
(cd ./books/1kings         && make)
(cd ./books/1peter         && make)
(cd ./books/1psalms        && make)
(cd ./books/1samuel        && make)
(cd ./books/1thessalonians && make)
(cd ./books/1timothy       && make)
(cd ./books/2acts          && make)
(cd ./books/2chronicles    && make)
(cd ./books/2corinthians   && make)
(cd ./books/2isaiah        && make)
(cd ./books/2john          && make)
(cd ./books/2john          && make)
(cd ./books/2kings         && make)
(cd ./books/2peter         && make)
(cd ./books/2peter         && make)
(cd ./books/2psalms        && make)
(cd ./books/2samuel        && make)
(cd ./books/2thessalonians && make)
(cd ./books/2thessalonians && make)
(cd ./books/2timothy       && make)
(cd ./books/3john          && make)
(cd ./books/3john          && make)
(cd ./books/3psalms        && make)
(cd ./books/4psalms        && make)
(cd ./books/5psalms        && make)
(cd ./books/amos           && make)
(cd ./books/colossians     && make)
(cd ./books/daniel         && make)
(cd ./books/deuteronomy    && make)
(cd ./books/ecclesiastes   && make)
(cd ./books/ephesians      && make)
(cd ./books/esther         && make)
(cd ./books/exodus         && make)
(cd ./books/ezekiel        && make)
(cd ./books/ezra           && make)
(cd ./books/galatians      && make)
(cd ./books/genesis        && make)
(cd ./books/habakkuk       && make)
(cd ./books/habakkuk       && make)
(cd ./books/haggai         && make)
(cd ./books/haggai         && make)
(cd ./books/hebrews        && make)
(cd ./books/hosea          && make)
(cd ./books/james          && make)
(cd ./books/james          && make)
(cd ./books/jeremiah       && make)
(cd ./books/job            && make)
(cd ./books/joel           && make)
(cd ./books/john           && make)
(cd ./books/jonah          && make)
(cd ./books/jonah          && make)
(cd ./books/joshua         && make)
(cd ./books/jude           && make)
(cd ./books/jude           && make)
(cd ./books/judges         && make)
(cd ./books/lamentations   && make)
(cd ./books/leviticus      && make)
(cd ./books/luke           && make)
(cd ./books/malachi        && make)
(cd ./books/mark           && make)
(cd ./books/mark           && make)
(cd ./books/matthew        && make)
(cd ./books/micah          && make)
(cd ./books/nahum          && make)
(cd ./books/nahum          && make)
(cd ./books/nehemiah       && make)
(cd ./books/numbers        && make)
(cd ./books/obadiah        && make)
(cd ./books/obadiah        && make)
(cd ./books/philemon       && make)
(cd ./books/philemon       && make)
(cd ./books/philippians    && make)
(cd ./books/proverbs       && make)
(cd ./books/psalm042       && make)
(cd ./books/psalm043       && make)
(cd ./books/psalm044       && make)
(cd ./books/psalm045       && make)
(cd ./books/psalm046       && make)
(cd ./books/psalm047       && make)
(cd ./books/psalm048       && make)
(cd ./books/psalm049       && make)
(cd ./books/psalm050       && make)
(cd ./books/psalm051       && make)
(cd ./books/psalm062       && make)
(cd ./books/revelation     && make)
(cd ./books/romans         && make)
(cd ./books/ruth           && make)
(cd ./books/song           && make)
(cd ./books/titus          && make)
(cd ./books/titus          && make)
(cd ./books/zechariah      && make)
(cd ./books/zephaniah      && make)
(cd ./books/zephaniah      && make)
