BOOK := BIBLE

include ../../common/make.common

SOURCES += ../../books/matthew/matthew.bible
SOURCES += ../../books/mark/mark.bible
SOURCES += ../../books/luke/luke.bible
SOURCES += ../../books/john/john.bible
SOURCES += ../../books/1acts/1acts.bible
SOURCES += ../../books/2acts/2acts.bible
SOURCES += ../../books/romans/romans.bible
SOURCES += ../../books/1corinthians/1corinthians.bible
SOURCES += ../../books/2corinthians/2corinthians.bible
SOURCES += ../../books/galatians/galatians.bible
SOURCES += ../../books/ephesians/ephesians.bible
SOURCES += ../../books/philippians/philippians.bible
SOURCES += ../../books/colossians/colossians.bible
SOURCES += ../../books/1thessalonians/1thessalonians.bible
SOURCES += ../../books/2thessalonians/2thessalonians.bible
SOURCES += ../../books/1timothy/1timothy.bible
SOURCES += ../../books/2timothy/2timothy.bible
SOURCES += ../../books/titus/titus.bible
SOURCES += ../../books/philemon/philemon.bible
SOURCES += ../../books/hebrews/hebrews.bible
SOURCES += ../../books/james/james.bible
SOURCES += ../../books/1peter/1peter.bible
SOURCES += ../../books/2peter/2peter.bible
SOURCES += ../../books/1john/1john.bible
SOURCES += ../../books/2john/2john.bible
SOURCES += ../../books/3john/3john.bible
SOURCES += ../../books/jude/jude.bible
SOURCES += ../../books/revelation/revelation.bible

# HISTORY
SOURCES += ../../books/genesis/genesis.bible
SOURCES += ../../books/exodus/exodus.bible
SOURCES += ../../books/leviticus/leviticus.bible
SOURCES += ../../books/numbers/numbers.bible
SOURCES += ../../books/deuteronomy/deuteronomy.bible
SOURCES += ../../books/joshua/joshua.bible
SOURCES += ../../books/judges/judges.bible
SOURCES += ../../books/ruth/ruth.bible
SOURCES += ../../books/1samuel/1samuel.bible
SOURCES += ../../books/2samuel/2samuel.bible
SOURCES += ../../books/1kings/1kings.bible
SOURCES += ../../books/2kings/2kings.bible
SOURCES += ../../books/1chronicles/1chronicles.bible
SOURCES += ../../books/2chronicles/2chronicles.bible
SOURCES += ../../books/ezra/ezra.bible
SOURCES += ../../books/nehemiah/nehemiah.bible
SOURCES += ../../books/esther/esther.bible
SOURCES += ../../books/job/job.bible
SOURCES += ../../books/1psalms/1psalms.bible
SOURCES += ../../books/psalm042/psalm042.bible
SOURCES += ../../books/psalm043/psalm043.bible
SOURCES += ../../books/psalm044/psalm044.bible
SOURCES += ../../books/psalm045/psalm045.bible
SOURCES += ../../books/psalm046/psalm046.bible
SOURCES += ../../books/psalm047/psalm047.bible
SOURCES += ../../books/psalm048/psalm048.bible
SOURCES += ../../books/psalm049/psalm049.bible
SOURCES += ../../books/psalm050/psalm050.bible
SOURCES += ../../books/psalm051/psalm051.bible
SOURCES += ../../books/psalm062/psalm062.bible
SOURCES += ../../books/2psalms/2psalms.bible
SOURCES += ../../books/3psalms/3psalms.bible
SOURCES += ../../books/4psalms/4psalms.bible
SOURCES += ../../books/5psalms/5psalms.bible
SOURCES += ../../books/proverbs/proverbs.bible
SOURCES += ../../books/song/song.bible
SOURCES += ../../books/ecclesiastes/ecclesiastes.bible
SOURCES += ../../books/1isaiah/1isaiah.bible
SOURCES += ../../books/2isaiah/2isaiah.bible
SOURCES += ../../books/jeremiah/jeremiah.bible
SOURCES += ../../books/lamentations/lamentations.bible
SOURCES += ../../books/ezekiel/ezekiel.bible
SOURCES += ../../books/daniel/daniel.bible
SOURCES += ../../books/hosea/hosea.bible
SOURCES += ../../books/joel/joel.bible
SOURCES += ../../books/amos/amos.bible
SOURCES += ../../books/obadiah/obadiah.bible
SOURCES += ../../books/jonah/jonah.bible
SOURCES += ../../books/micah/micah.bible
SOURCES += ../../books/nahum/nahum.bible
SOURCES += ../../books/habakkuk/habakkuk.bible
SOURCES += ../../books/zephaniah/zephaniah.bible
SOURCES += ../../books/haggai/haggai.bible
SOURCES += ../../books/zechariah/zechariah.bible
SOURCES += ../../books/malachi/malachi.bible

$(BOOK).bible: $(SOURCES)
	rm -f $@
	cat $^ > $@
	chmod 444 $@

