= The Creation Week
:doctype: book
:toc:     right

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= In the Beginning

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I am Don from Colorado and I am beginning something new.

God's Word begins with the book of Genesis,
so I will begin in Genesis.

== Read Text

> In the beginning, +
> God created the heavens and the earth. +
>
> The earth was without form and void. +
>
> Darkness was on the surface of the deep +
> and God's Spirit was hovering over the surface of the waters.

== Teaching

=== In the Beginning

> In the beginning

> In the beginning

=== Day Zero

Day zero.

> God created the heavens and the earth.

That means before day zero was God.

And on Day Zero, God create the heavens and the earth.

TIP: Day zero

TIP: God

=== Without Form and Void

The earth at this very beginning that God just created
was without form and void.

=== Darkness on the Surface of the Deep

Darkness was on the surface of the deep.

And God's Spirit --- also here ---
was hovering over the surface of the waters.

=== God, God's Spirit

TIP: God's Spirit

The picture here ---
at the very beginning ---
the creator God creates ---
but He creates something that is not fully formed ---
in fact, `without form and void`.

Full of darkness.

He is there.
His Spirit is there.
Water is there.
And the heavens and earth were surrounded with darkness.

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

=== Father God

=== You are the creator who has great power.

=== You tell us these things, connecting us to the beginning.

=== Do a work in me.

=== Open my eyes.

=== ''And He will speak peace to the nations.'' (Zech 9:10b)

== Closing Comments

This is just the first step.

We'll continue to look at God's Word -- reading, thinking, and praying.

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= The First Day of Creation

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I'm Don from Colorado.

ABCD = Another Beautiful Colorado Day

== Read Text

> God said, +
>
> > Let there be light, +
>
> and there was light. +
>
> And God saw the light, +
> and saw that it was good. +
>
> God divided the light from the darkness. +
>
> God called the light Day, +
> and the darkness he called Night. +
>
> There was evening and there was morning, +
> the first day. +

== Teaching

=== God Speaks Light into Existence

=== Creator Creating

> God said, +
>
> > Let there be light, +
>
> and there was light. +

=== Creator Assessing

> And God saw the light, +
> and saw that it was good. +

=== Creator Structuring

> God divided the light from the darkness.

=== Creator Naming

> God called the light Day, +
> and the darkness he called Night. +

=== 24-Hour Clock

> There was evening and there was morning, +
> the first day. +

=== The Word was with God

> In the beginning was the Word, +
> and the Word was with God, +
> and the Word was God. +

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= The Second Day of Creation

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

== Read Text

== Teaching

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= The Third Day of Creation

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I'm Don from Colorado.

ABCD = Another Beautiful Colorado Day

== Read Text

== Teaching

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= The Fourth Day of Creation

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I'm Don from Colorado.

ABCD = Another Beautiful Colorado Day

== Read Text

> God said, +
>
> > Let there be lights +
> > in the expanse of the sky +
> > to divide the day from the night; +
> > and let them be for signs +
> > to mark seasons, days, and years; +
> > and let them be for lights +
> > in the expanse of the sky +
> > to give light on the earth; +
>
> and it was so. +
>
> God made the two great lights: +
> the greater light to rule the day, +
> and the lesser light to rule the night. +
>
> He also made the stars. +
>
> God set them in the expanse of the sky +
> to give light to the earth, +
> and to rule over the day and over the night, +
> and to divide the light from the darkness. +
>
> God saw that it was good. +
>
> There was evening and there was morning, +
> a fourth day. +

== Teaching

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

=== Fourth Day of Creation

This is the Fourth Day of Creation.

TIP: lights

TIP: PURPOSE: to divide the day from the night

TIP: PURPOSE: to give light on the earth

TIP: for signs to mark seasons, days, and years

=== Fourth Day of Creation

God identifies this as the Fourth Day of Creation:

== Pray Briefly

- Father God

- You are the creator who has great power.

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= The Fifth Day of Creation

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I'm Don from Colorado.

ABCD = Another Beautiful Colorado Day

== Read Text

> God said, +
>
> > Let the waters abound with living creatures, +
> > and let birds fly above the earth +
> > in the open expanse of the sky. +
>
> God created the large sea creatures +
> and every living creature that moves, +
> with which the waters swarmed, +
>   after their kind, +
> and every winged bird +
>   after its kind. +
>
> God saw that it was good. +
>
> God blessed them, saying, +
>
> > Be fruitful, +
> > and multiply, +
> > and fill the waters in the seas, +
> > and let birds multiply on the earth. +
>
> There was evening and there was morning, +
> a fifth day.

== Teaching

=== Fifth Day of Creation

What do we see here in the text on the Fifth Day of Creation?

As is the pattern throughout these first days of creation,
God says something --- He speaks ---
that something should exist...
Let it exist.
That's a creation act.

So what does He create on the fifth day?

The text tells us...

[quote]
God created the large sea creatures +
and every living creature that moves, +
with which the waters swarmed, +
after their kind, +

TIP: sea creatures

[quote]
and every winged bird +
after its kind. +

TIP: birds

=== Every Kind

You know what?
I have not noticed before ---
in my sometimes-too-rapid reading method ---
is the word `every`.

It's used `twice` here.

`Every` living creature that moves,
with which the waters swarmed.

TIP: every

`Every` winged bird after its kind.

TIP: every

This word `every` is a profound word.
And it's a word that I have missed in the past.

But what this is saying then is that every winged bird is
created in the fifth day of creation.

==== Example: Sparrow

So let's take one example of a common bird.

Let's think of the sparrow.

This kind that we call `sparrow` was created here on the Fifth Day of Creation.

In our modern terminology, we say the gene pool of the sparrow was created here
on the Fifth Day of Creation.

But the kind being created,
it took time for different kinds of sparrows to become evident.

* sparrow
** house sparrow
** field sparrow
** song sparrow

And the same is true of every bird and every sea creature.

All of the kinds of sea creatures and birds
were created on this Fifth Day of Creation.

That is a profound thought.

I don't remember thinking about this before.

It never jumped out at me from the text before.

=== God Saw

God assesses.

[quote]
God *saw* that it was good.

God, being the creator, assesses.

This also jumps out at me here for the first time.

This text could have been worded: ''And it was good.''

==== Theme

There is a theme here.

[quote]
God *saw* that it was good.

NOTE: Go to Day Four of Creation.

[quote]
God *saw* that it was good.

NOTE: Go to Day Three of Creation.

[quote]
God *saw* that it was good.

There is a theme here across the Days of Creation.

==== Hmmm

I learn more by reading this out loud and thinking out loud
with the possibility of teaching others.

Each day of creation has had a similar line.

[quote]
God *saw* that it was good.

God looks at his creation and assesses His creation.

==== The Maker of a Pot

Imagine a person who has created a clay pot.

He's all done with his pot and he sets it in front of himself on the table,
then he says, ''That's good.''

That's what we have here.

God looks at His creation after each day and assesses it.

[quote]
God *saw* that it was good.

=== Bless and Commands

Then we come to these words:

[quote]
God blessed them, saying, +
''Be fruitful, +
  and multiply, +
  and fill the waters in the seas, +
  and let birds multiply on the earth.''

The text says God `blessed` these creatures.

This is a blessing
that these sea creatures will multiply and fill the waters in the seas
and the birds will multiply on the earth.

But these words are stated as commands to these creatures:

[quote]
''*Be fruitful*, +
  and *multiply*, +
  and *fill* the waters in the seas, +
  and let birds multiply on the earth.''

I understand God blessing these creatures,
but a creature cannot be commanded
in the same way that a person can be commanded.

It must be that this command is an expression of God's purpose,
similar to the Fourth Day of Creation when
God said that the sun, moon, and stars were created with a purpose:

[quote]
  Let there be lights +
  in the expanse of the sky +
  to divide the day from the night; +
  and let them be for signs +
  *to mark* seasons, days, and years;

God created these creatures with a nature
to have babies
and to protect their young,
so that the Earth would be full of these creatures.

God's command informs mankind
that this is his desire for these creatures.

Let's notate this as B/C for ''Bless/Command''.

=== Repetition --- Multiply

We have a repetition here again:

[quote]
God blessed them, saying, +
''Be fruitful, +
  and *multiply*, +
  and fill the waters in the seas, +
  and let birds *multiply* on the earth.''

Multiply and fill.

=== Fifth Day of Creation

God identifies this as the Fifth Day of Creation:

> There was evening and there was morning, +
> a fifth day.

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

- Father God

- You are a great God who is able to create every kind
  of sea creatures and birds in a single day.

- I thank you for telling me that it is your purpose
  that these creatures would fill the Earth.

- Thank you for being the God who created life.
  We humans cannot create life.
  Only you can do this.
  Life has not come about by chance.

- Thank you for connecting me to the beginning
  when you created the heavens and the earth.

- I pray that Your words would continue to jump off the page
  as I continue to read and think about your Word.

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= The Sixth Day of Creation

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I'm Don from Colorado.

ABCD = Another Beautiful Colorado Day

== Read Text

== Teaching

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= The Seventh Day

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I'm Don from Colorado.

ABCD = Another Beautiful Colorado Day

== Read Text

== Teaching

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

== Summary

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
= Template

== Good Morning

It's 9:00 AM on Monday, January 9th, 2023.

I'm Don from Colorado.

ABCD = Another Beautiful Colorado Day

== Read Text

== Teaching

== Summary

=== Days of Creation

[cols="1,10"]
|===
|Day | Created

| 0 | God created heavens and earth -- without form and void

| 1 | Light -- separated light (Day) from darkness (Night)

| 2 | Expanse in the midst of the waters (Sky, Atmosphere)

| 3 | Seas, Dry Land (Earth)

| 4 | Greater Light (Sun), Lesser Light (Moon), Stars

| 5 | Sea Creatures, Birds

| 6 | Land animals, Man (Adam, Eve)

| 7 | Sabbath
|===

=== Creator Rights

[cols="3,8"]
|===
|Creator Rights        | Example

|Creating              | God said, ''Let there be light.''

|Assessing             | God *saw* that it was *good*.

|Structuring           | God *divided* the light from the dark.

|Naming                | God *called* the light Day and the evening He *called* Night.

|Blessing / Commanding |
|===

== Pray Briefly

== Blessing

[quote]
The LORD bless you and keep you. +
The LORD make his face shine upon you, +
and be gracious to you. +
The LORD lift up His countenance upon you, +
and give you peace.

